### ISSUE TITLE
Samurai客户端资源消耗是否可以降低？

### ISSUE THREAD

**Issue by xxgoracle** [PlatONnetwork/Samurai#13]
![图片](https://user-images.githubusercontent.com/26682628/54577630-7c440500-4a37-11e9-936d-3a35bbc1e2c8.png)
1. 运行Samurai客户端资源使用比较高，下一个版本可以降低吗？
2. 什么时候可以得到优化？

**Comment by danielgogo** [comment]
0.6.0版本已经改善
