### ISSUE TITLE
windows客户端，无法选定区块存储路径

### ISSUE THREAD

**Issue by shiknian** [PlatONnetwork/Samurai#15]
![image](https://user-images.githubusercontent.com/28284045/54595578-e081bb80-4a6d-11e9-97bd-2494835a3f7a.png)

windows软件无法修改安装路径，从而导致C盘空间不足

**Comment by shiknian** [comment]
这样设计肯定是不合理的，这里应该是个bug问题

**Comment by cool007zqw** [comment]
有一个办法，用mklink把这个文件夹链接到其它分区

可以参考这里：https://www.cnblogs.com/plusium/archive/2010/03/17/1688511.html

**Comment by danielgogo** [comment]
非常感谢，我们会参考下。 0.6.0的版本已经自定义数据目录
